
port: 7890
allow-lan: false
mode: rule
log-level: silent
ipv6: true

proxies:
  - name: LIMITLESS STREAMING GP
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"
  
  - name: LIMITLESS SOCIAL GP
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"
  
  - name: LIMITLESS STREAMING ROBI
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"

  - name: LIMITLESS STREEAMING BL
    type: vmess
    server: 
    port: 4442
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"
        
proxy-groups:
  - name: BDCLOUD
    type: select
    proxies:
      - DIRECT
      - LIMITLESS STREAMING GP
      - LIMITLESS SOCIAL GP
      - LIMITLESS STREAMING ROBI
      - LIMITLESS STREEAMING BL

rules:
  #  - SCRIPT,NULLDNS,REJECT 
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - IP-CIDR,172.16.50.7/24,BDCLOUD
  - MATCH,BDCLOUD
