port: 7890
allow-lan: false
mode: rule
log-level: silent
ipv6: true

proxies:
  - name: GP STREAMING
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.youtube.com"
  
  - name: GP SOCIAL
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.instagram.com"
  
  - name: ROBI STREAMING
    type: vmess
    server: 
    port: 
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.snapchat.com"

  - name: ROBI SOCIAL
    type: vmess
    server: 
    port: 4442
    uuid: 
    alterId: 0
    cipher: auto
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: "/vmess"
      headers:
        Host: "www.instagram.com"
        
proxy-groups:
  - name: BDCLOUD
    type: select
    proxies:
      - DIRECT
      - GP STREAMING
      - GP SOCIAL
      - ROBI STREAMING
      - ROBI SOCIAL

rules:
  #  - SCRIPT,NULLDNS,REJECT 
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - IP-CIDR,172.16.50.7/24,BDCLOUD
  - MATCH,BDCLOUD
