version: '3.8'
services:
  clash-config-generator:
    container_name: clash-config-generator
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - GUNICORN_CMD_ARGS="--limit-request-line 8190 --limit-request-field_size 8190"
