services:
  clash-config-generator:
    container_name: clash-config-generator
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      bash -c "ls" &&
      bash -c "pip install flask pyyaml" &&
      bash -c "python main.py"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
