services:
  clash-config-generator:
    container_name: clash-config-generator
    build: .
    ports:
      - "5000:5000"
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "main:app"]
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
