services:
  clash-config-generator:
    container_name: clash-config-generator
    image: python:3.9-slim
    working_dir: /app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install --no-cache-dir flask pyyaml gunicorn && python main.py"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
